version: '3'
services:
  client:
    image: 17cl/katamino-client
    ports:
      - 3000:3000
    build:
      context: ./client
    depends_on:
      - solver
  solver:
    image: 17cl/katamino-solver
    build:
      context: ./solver
    ports:
      - 8080:8080
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client