version: '3'
services:
  client:
    image: 17cl/katamino-client
    build:
      context: ./client
  solver:
    image: 17cl/katamino-solver
    build:
      context: ./solver
    ports:
      - 8080:8080